### ISSUE TITLE
[Feature request] Loading List

### ISSUE THREAD

**Issue by maverick74** [ettoolong/PopupVideo#5]
Would be good to have a loading list.

it would be nice if one could go to, for example, YouTube and create a list of videos one wants to see

Similar feature is available in Mozilla's (soon to be disabled) Min Vid

**Comment by ettoolong** [comment]
Sorry, if you need full feature for playlist management ( UI that support add/delete/sort/share etc.), you should install Min Vid. Min Vid is a complicated add-on that MANY contributors work on it for two years (support youtube/vimeo/soundcloud).

If you open PopupVideo from youtube playlist, the PopupVideo will play all video in the list one by one.
PopupVideo is an lite weight add-on for watching video, I only provide the most basic feature on it.
I create PopupVideo because I don't need some functions that Min Vid provided.

Thank you.

**Comment by maverick74** [comment]
I was not aware that opening PopupVideo from youtube playlist, the PopupVideo will play all video in the list one by one.

that will do the trick ;)

Still, would be good to add that trick in the addon's description.

thank you :D
